# Challenge Pt 1

In [1]:
# First I need to get data..... uhhh...
# Specifically weather description and precipitation on cities...?

from citipy import citipy
import numpy as np
import pandas as pd

In [2]:
# Set of random latitiude and longitiudes
lats = np.random.uniform(low = -90.000, high = 90.000, size=1500)
lngs = np.random.uniform(low = -180.000, high = 180.000, size =1500)
lat_lngs = zip(lats,lngs)

In [3]:
# Create coordinates by adding lats and lngs to a list
coordinates = list(lat_lngs)

In [7]:
# Creaing list for generated cities from lats lngs list.
cities = []

# ID the closest city for the coordinates
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name
    
    # if city is unique then add it to the cities list
    if city not in cities:
        cities.append(city)

len(cities)

596

In [8]:
# Import request library
import requests

from datetime import datetime

from config import weather_api_key

In [13]:
url = f"http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID={weather_api_key}"

# link showed 400 all good so far.... T.T

http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=3ed7f2b9881e5ce09b00b900c6320bc5

In [23]:
# City Data List
city_data=[]
#Print to log
print("Beginning Data Retrieval")
print("-"*20)

# Create counter
record_count = 1
set_count =1
for index, city in enumerate(cities):
    
    # Group Cities in sets of 50
    if(index % 50 == 0 and index >= 50):
        set_count+=1
        record_count =1
     # Create endpoint URL with each city
    city_url = f'{url}&q={city.replace(" ", "+")}'
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    
    record_count +=1
    
    #Store into list
    try:
        city_weather = requests.get(city_url).json()
        # Parse out the max temp, humidity, clouds (extracting keys)
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        city_weather_description = city_weather["weather"][0]["description"]
        try:
            city_rain_inches = city_weather["rain"]["1h"]
        except KeyError:
            city_rain_inches = 0
            
        try:
            city_snow_inches = city_weather["rain"]["1h"]
        except KeyError:
            city_snow_inches = 0
            
        #Append the city information into city_data
        city_data.append(
        {
            "City": city,
            "Lat": city_lat,
            "Lng": city_lng,
            "Max Temp": city_max_temp,
            "Current Description": city_weather_description,
            "Rain (inches)": city_rain_inches,
            "Snow (inches)": city_snow_inches,
            "Humidity": city_humidity,
            "Cloudiness": city_clouds,
            "Wind Speed": city_wind,
            "Country": city_country
        })
    except:
        print("City not found. Skipping...")
        pass
# Indicates that the data loading is done
print("-"*20)
print("Data Retrieval is Complete")
print("-"*20)

Beginning Data Retrieval
--------------------
Processing Record 1 of Set 1 | ler
Processing Record 2 of Set 1 | mount gambier
Processing Record 3 of Set 1 | illoqqortoormiut
City not found. Skipping...
Processing Record 4 of Set 1 | chokurdakh
Processing Record 5 of Set 1 | tateyama
Processing Record 6 of Set 1 | kaman
Processing Record 7 of Set 1 | ushuaia
Processing Record 8 of Set 1 | villarrica
Processing Record 9 of Set 1 | necochea
Processing Record 10 of Set 1 | luganville
Processing Record 11 of Set 1 | jamestown
Processing Record 12 of Set 1 | hermanus
Processing Record 13 of Set 1 | platon sanchez
Processing Record 14 of Set 1 | katete
Processing Record 15 of Set 1 | albany
Processing Record 16 of Set 1 | kudat
Processing Record 17 of Set 1 | tasiilaq
Processing Record 18 of Set 1 | kharian
Processing Record 19 of Set 1 | busselton
Processing Record 20 of Set 1 | trondheim
Processing Record 21 of Set 1 | belushya guba
City not found. Skipping...
Processing Record 22 of Set 1 | saskylakh
Processing Record 23 of Set 1 | grand-santi
Processing Record 24 of Set 1 | bethel
Processing Record 25 of Set 1 | rikitea
Processing Record 26 of Set 1 | kruisfontein
Processing Record 27 of Set 1 | barrow
Processing Record 28 of Set 1 | sabha
Processing Record 29 of Set 1 | mataura
Processing Record 30 of Set 1 | ancud
Processing Record 31 of Set 1 | tutoia
Processing Record 32 of Set 1 | puerto ayora
Processing Record 33 of Set 1 | broome
Processing Record 34 of Set 1 | cabo san lucas
Processing Record 35 of Set 1 | kodiak
Processing Record 36 of Set 1 | punta arenas
Processing Record 37 of Set 1 | usogorsk
Processing Record 38 of Set 1 | saleaula
City not found. Skipping...
Processing Record 39 of Set 1 | butaritari
Processing Record 40 of Set 1 | chute-aux-outardes
Processing Record 41 of Set 1 | mount isa
Processing Record 42 of Set 1 | clyde river
Processing Record 43 of Set 1 | atuona
Processing Record 44 of Set 1 | taolanaro
City not found. Skipping...
Processing Record 45 of Set 1 | ahipara
Processing Record 46 of Set 1 | bluff
Processing Record 47 of Set 1 | concepcion del oro
Processing Record 48 of Set 1 | port alfred
Processing Record 49 of Set 1 | george
Processing Record 50 of Set 1 | wawa
Processing Record 1 of Set 2 | beruni
City not found. Skipping...
Processing Record 2 of Set 2 | acapulco
Processing Record 3 of Set 2 | bathsheba
Processing Record 4 of Set 2 | nemuro
Processing Record 5 of Set 2 | isla mujeres
Processing Record 6 of Set 2 | arraial do cabo
Processing Record 7 of Set 2 | san pedro de uraba
Processing Record 8 of Set 2 | thinadhoo
Processing Record 9 of Set 2 | adrar
Processing Record 10 of Set 2 | aripuana
Processing Record 11 of Set 2 | saint anthony
Processing Record 12 of Set 2 | saldanha
Processing Record 13 of Set 2 | cape town
Processing Record 14 of Set 2 | longyearbyen
Processing Record 15 of Set 2 | ilulissat
Processing Record 16 of Set 2 | bourail
Processing Record 17 of Set 2 | thompson
Processing Record 18 of Set 2 | khatanga
Processing Record 19 of Set 2 | shimoda
Processing Record 20 of Set 2 | vaini
Processing Record 21 of Set 2 | hokitika
Processing Record 22 of Set 2 | georgetown
Processing Record 23 of Set 2 | tabory
Processing Record 24 of Set 2 | east london
Processing Record 25 of Set 2 | victoria
Processing Record 26 of Set 2 | sinnamary
Processing Record 27 of Set 2 | avarua
Processing Record 28 of Set 2 | camana
Processing Record 29 of Set 2 | tiksi
Processing Record 30 of Set 2 | nikolskoye
Processing Record 31 of Set 2 | kahului
Processing Record 32 of Set 2 | voskresenskoye
Processing Record 33 of Set 2 | airai
Processing Record 34 of Set 2 | venice
Processing Record 35 of Set 2 | cidreira
Processing Record 36 of Set 2 | qaanaaq
Processing Record 37 of Set 2 | lima
Processing Record 38 of Set 2 | komsomolskiy
Processing Record 39 of Set 2 | chuy
Processing Record 40 of Set 2 | barentsburg
City not found. Skipping...
Processing Record 41 of Set 2 | dikson
Processing Record 42 of Set 2 | beringovskiy
Processing Record 43 of Set 2 | ngukurr
City not found. Skipping...
Processing Record 44 of Set 2 | kushima
Processing Record 45 of Set 2 | kholm
Processing Record 46 of Set 2 | kapaa
Processing Record 47 of Set 2 | port keats
Processing Record 48 of Set 2 | luderitz
Processing Record 49 of Set 2 | frankfurt
Processing Record 50 of Set 2 | souillac
Processing Record 1 of Set 3 | gikongoro
Processing Record 2 of Set 3 | provideniya
Processing Record 3 of Set 3 | marataizes
Processing Record 4 of Set 3 | huarmey
Processing Record 5 of Set 3 | kavaratti
Processing Record 6 of Set 3 | bure
Processing Record 7 of Set 3 | pitimbu
Processing Record 8 of Set 3 | balimo
City not found. Skipping...
Processing Record 9 of Set 3 | sainte-marie
Processing Record 10 of Set 3 | hilo
Processing Record 11 of Set 3 | tuktoyaktuk
Processing Record 12 of Set 3 | terenos
Processing Record 13 of Set 3 | povenets
Processing Record 14 of Set 3 | castro
Processing Record 15 of Set 3 | carnarvon
Processing Record 16 of Set 3 | hambantota
Processing Record 17 of Set 3 | abu samrah
Processing Record 18 of Set 3 | north bend
Processing Record 19 of Set 3 | mergui
City not found. Skipping...
Processing Record 20 of Set 3 | barawe
City not found. Skipping...
Processing Record 21 of Set 3 | gladstone
Processing Record 22 of Set 3 | torbay
Processing Record 23 of Set 3 | ballater
Processing Record 24 of Set 3 | hithadhoo
Processing Record 25 of Set 3 | ostrovnoy
Processing Record 26 of Set 3 | khandyga
Processing Record 27 of Set 3 | atar
Processing Record 28 of Set 3 | ponta do sol
Processing Record 29 of Set 3 | kaitangata
Processing Record 30 of Set 3 | gat
Processing Record 31 of Set 3 | alekseyevskoye
Processing Record 32 of Set 3 | grindavik
Processing Record 33 of Set 3 | mys shmidta
City not found. Skipping...
Processing Record 34 of Set 3 | jiazi
Processing Record 35 of Set 3 | fortuna
Processing Record 36 of Set 3 | saint-augustin
Processing Record 37 of Set 3 | kavieng
Processing Record 38 of Set 3 | leningradskiy
Processing Record 39 of Set 3 | lorengau
Processing Record 40 of Set 3 | hobart
Processing Record 41 of Set 3 | pevek
Processing Record 42 of Set 3 | port hardy
Processing Record 43 of Set 3 | sao miguel do araguaia
Processing Record 44 of Set 3 | lake havasu city
Processing Record 45 of Set 3 | koslan
Processing Record 46 of Set 3 | santiago
Processing Record 47 of Set 3 | uruguaiana
Processing Record 48 of Set 3 | jalu
Processing Record 49 of Set 3 | port elizabeth
Processing Record 50 of Set 3 | prince rupert
Processing Record 1 of Set 4 | concepcion
Processing Record 2 of Set 4 | norman wells
Processing Record 3 of Set 4 | upernavik
Processing Record 4 of Set 4 | homer
Processing Record 5 of Set 4 | tsihombe
City not found. Skipping...
Processing Record 6 of Set 4 | port hedland
Processing Record 7 of Set 4 | kuche
City not found. Skipping...
Processing Record 8 of Set 4 | ksenyevka
City not found. Skipping...
Processing Record 9 of Set 4 | chippewa falls
Processing Record 10 of Set 4 | kanniyakumari
Processing Record 11 of Set 4 | mar del plata
Processing Record 12 of Set 4 | bontang
Processing Record 13 of Set 4 | chegutu
Processing Record 14 of Set 4 | samusu
City not found. Skipping...
Processing Record 15 of Set 4 | marechal floriano
Processing Record 16 of Set 4 | cayenne
Processing Record 17 of Set 4 | soyo
Processing Record 18 of Set 4 | cherskiy
Processing Record 19 of Set 4 | naze
Processing Record 20 of Set 4 | kyren
Processing Record 21 of Set 4 | tulle
Processing Record 22 of Set 4 | tommot
Processing Record 23 of Set 4 | new norfolk
Processing Record 24 of Set 4 | mbour
Processing Record 25 of Set 4 | half moon bay
Processing Record 26 of Set 4 | buon me thuot
City not found. Skipping...
Processing Record 27 of Set 4 | san quintin
Processing Record 28 of Set 4 | abha
Processing Record 29 of Set 4 | vysokogornyy
Processing Record 30 of Set 4 | saiki
Processing Record 31 of Set 4 | waipawa
Processing Record 32 of Set 4 | asau
Processing Record 33 of Set 4 | taltal
Processing Record 34 of Set 4 | hasaki
Processing Record 35 of Set 4 | pilar
Processing Record 36 of Set 4 | saint-philippe

Processing Record 37 of Set 4 | quang ngai
Processing Record 38 of Set 4 | alice springs
Processing Record 39 of Set 4 | caravelas
Processing Record 40 of Set 4 | santo domingo
Processing Record 41 of Set 4 | tongliao
Processing Record 42 of Set 4 | katsuura
Processing Record 43 of Set 4 | lebu
Processing Record 44 of Set 4 | sentyabrskiy
City not found. Skipping...
Processing Record 45 of Set 4 | zapolyarnyy
Processing Record 46 of Set 4 | bengkulu
Processing Record 47 of Set 4 | mocuba
Processing Record 48 of Set 4 | kangaatsiaq
Processing Record 49 of Set 4 | bambous virieux
Processing Record 50 of Set 4 | severo-kurilsk
Processing Record 1 of Set 5 | sochi
Processing Record 2 of Set 5 | zhicheng
Processing Record 3 of Set 5 | san cristobal
Processing Record 4 of Set 5 | warqla
City not found. Skipping...
Processing Record 5 of Set 5 | saint-max
Processing Record 6 of Set 5 | ola
Processing Record 7 of Set 5 | bredasdorp
Processing Record 8 of Set 5 | natal
Processing Record 9 of Set 5 | anadyr
Processing Record 10 of Set 5 | okhotsk
Processing Record 11 of Set 5 | palaiokhora
City not found. Skipping...
Processing Record 12 of Set 5 | palabuhanratu
City not found. Skipping...
Processing Record 13 of Set 5 | takaka
Processing Record 14 of Set 5 | yellowknife
Processing Record 15 of Set 5 | buraydah
Processing Record 16 of Set 5 | nagyoroszi
Processing Record 17 of Set 5 | bilma
Processing Record 18 of Set 5 | xai-xai
Processing Record 19 of Set 5 | portland
Processing Record 20 of Set 5 | zeya
Processing Record 21 of Set 5 | constitucion
Processing Record 22 of Set 5 | barvinkove
Processing Record 23 of Set 5 | salalah
Processing Record 24 of Set 5 | iqaluit
Processing Record 25 of Set 5 | goderich
Processing Record 26 of Set 5 | umm kaddadah
Processing Record 27 of Set 5 | pisco
Processing Record 28 of Set 5 | dayong
Processing Record 29 of Set 5 | canico
Processing Record 30 of Set 5 | along
Processing Record 31 of Set 5 | nelson bay
Processing Record 32 of Set 5 | talnakh
Processing Record 33 of Set 5 | huelva
Processing Record 34 of Set 5 | ambon
Processing Record 35 of Set 5 | amderma
City not found. Skipping...
Processing Record 36 of Set 5 | tazovskiy
Processing Record 37 of Set 5 | warren
Processing Record 38 of Set 5 | abu zabad
Processing Record 39 of Set 5 | tessalit
Processing Record 40 of Set 5 | rawannawi
City not found. Skipping...
Processing Record 41 of Set 5 | moron
Processing Record 42 of Set 5 | poykovskiy
Processing Record 43 of Set 5 | klaksvik
Processing Record 44 of Set 5 | dingle
Processing Record 45 of Set 5 | zhigalovo
Processing Record 46 of Set 5 | pokhara
Processing Record 47 of Set 5 | faanui
Processing Record 48 of Set 5 | tripoli
Processing Record 49 of Set 5 | port blair
Processing Record 50 of Set 5 | manta
Processing Record 1 of Set 6 | nanortalik
Processing Record 2 of Set 6 | assare
Processing Record 3 of Set 6 | mormugao
Processing Record 4 of Set 6 | korla
Processing Record 5 of Set 6 | port augusta
Processing Record 6 of Set 6 | akdepe
Processing Record 7 of Set 6 | ratnagiri
Processing Record 8 of Set 6 | ribeira grande
Processing Record 9 of Set 6 | neyyattinkara
Processing Record 10 of Set 6 | olinda
Processing Record 11 of Set 6 | nanga eboko
Processing Record 12 of Set 6 | eureka
Processing Record 13 of Set 6 | inirida
Processing Record 14 of Set 6 | cangucu
Processing Record 15 of Set 6 | tabiauea
City not found. Skipping...
Processing Record 16 of Set 6 | hovd
Processing Record 17 of Set 6 | toliary
City not found. Skipping...
Processing Record 18 of Set 6 | kendari
Processing Record 19 of Set 6 | saint george
Processing Record 20 of Set 6 | say
Processing Record 21 of Set 6 | sofiysk
City not found. Skipping...
Processing Record 22 of Set 6 | neiafu
Processing Record 23 of Set 6 | maragogi
Processing Record 24 of Set 6 | jiroft
City not found. Skipping...
Processing Record 25 of Set 6 | mandalgovi
Processing Record 26 of Set 6 | windhoek
Processing Record 27 of Set 6 | sainte-thecle
Processing Record 28 of Set 6 | biltine
Processing Record 29 of Set 6 | lisakovsk
Processing Record 30 of Set 6 | mao
Processing Record 31 of Set 6 | taraz
Processing Record 32 of Set 6 | nome
Processing Record 33 of Set 6 | yongan
Processing Record 34 of Set 6 | grand river south east
City not found. Skipping...
Processing Record 35 of Set 6 | xining
Processing Record 36 of Set 6 | kaitong
Processing Record 37 of Set 6 | nador
Processing Record 38 of Set 6 | san juan
Processing Record 39 of Set 6 | poum
Processing Record 40 of Set 6 | esperance
Processing Record 41 of Set 6 | attawapiskat
City not found. Skipping...
Processing Record 42 of Set 6 | erzin
Processing Record 43 of Set 6 | palmerston
Processing Record 44 of Set 6 | flin flon
Processing Record 45 of Set 6 | wajima
Processing Record 46 of Set 6 | sur
Processing Record 47 of Set 6 | artyk
City not found. Skipping...
Processing Record 48 of Set 6 | yellandu
Processing Record 49 of Set 6 | kiruna
Processing Record 50 of Set 6 | tianpeng
Processing Record 1 of Set 7 | barra do garcas
Processing Record 2 of Set 7 | madison
Processing Record 3 of Set 7 | tawang
Processing Record 4 of Set 7 | taburi
City not found. Skipping...
Processing Record 5 of Set 7 | arlit
Processing Record 6 of Set 7 | nyurba
Processing Record 7 of Set 7 | dunmore town
Processing Record 8 of Set 7 | cao bang
Processing Record 9 of Set 7 | samarai
Processing Record 10 of Set 7 | timra
Processing Record 11 of Set 7 | gilgil
City not found. Skipping...
Processing Record 12 of Set 7 | gambela
Processing Record 13 of Set 7 | puerto colombia
Processing Record 14 of Set 7 | kyakhta
Processing Record 15 of Set 7 | lompoc
Processing Record 16 of Set 7 | san patricio
Processing Record 17 of Set 7 | mahajanga
Processing Record 18 of Set 7 | taksimo
Processing Record 19 of Set 7 | hutchinson
Processing Record 20 of Set 7 | gobo
Processing Record 21 of Set 7 | guerrero negro
Processing Record 22 of Set 7 | kayasula
Processing Record 23 of Set 7 | karratha
Processing Record 24 of Set 7 | tahta
Processing Record 25 of Set 7 | kudahuvadhoo
Processing Record 26 of Set 7 | omboue
Processing Record 27 of Set 7 | rangpo
Processing Record 28 of Set 7 | yar-sale
Processing Record 29 of Set 7 | bafq
Processing Record 30 of Set 7 | kyshtovka
Processing Record 31 of Set 7 | palmer
Processing Record 32 of Set 7 | plouzane
Processing Record 33 of Set 7 | kirkuk
Processing Record 34 of Set 7 | dezhou
Processing Record 35 of Set 7 | coihaique
Processing Record 36 of Set 7 | andenes
Processing Record 37 of Set 7 | martapura
Processing Record 38 of Set 7 | olafsvik
Processing Record 39 of Set 7 | bonavista
Processing Record 40 of Set 7 | haimen
Processing Record 41 of Set 7 | saravan
Processing Record 42 of Set 7 | pryozerne
Processing Record 43 of Set 7 | hamilton
Processing Record 44 of Set 7 | codrington
Processing Record 45 of Set 7 | san roque
Processing Record 46 of Set 7 | tongzi
Processing Record 47 of Set 7 | ji-parana
City not found. Skipping...
Processing Record 48 of Set 7 | stantsionno-oyashinskiy
Processing Record 49 of Set 7 | celestun
Processing Record 50 of Set 7 | mahebourg
Processing Record 1 of Set 8 | sibolga
Processing Record 2 of Set 8 | lolua
City not found. Skipping...
Processing Record 3 of Set 8 | liverpool
Processing Record 4 of Set 8 | hobyo
Processing Record 5 of Set 8 | batemans bay
Processing Record 6 of Set 8 | cabedelo
Processing Record 7 of Set 8 | geraldton
Processing Record 8 of Set 8 | boyuibe
Processing Record 9 of Set 8 | jatibonico
Processing Record 10 of Set 8 | taoudenni
Processing Record 11 of Set 8 | le port
Processing Record 12 of Set 8 | kota belud
Processing Record 13 of Set 8 | pangody
Processing Record 14 of Set 8 | tlahualilo
City not found. Skipping...
Processing Record 15 of Set 8 | halalo
City not found. Skipping...
Processing Record 16 of Set 8 | boa viagem
Processing Record 17 of Set 8 | vao
Processing Record 18 of Set 8 | los llanos de aridane
Processing Record 19 of Set 8 | banyo
Processing Record 20 of Set 8 | mehamn
Processing Record 21 of Set 8 | djougou
Processing Record 22 of Set 8 | mitsamiouli
Processing Record 23 of Set 8 | namibe
Processing Record 24 of Set 8 | banda aceh

Processing Record 25 of Set 8 | takoradi
Processing Record 26 of Set 8 | ciudad bolivar
Processing Record 27 of Set 8 | longlac
City not found. Skipping...
Processing Record 28 of Set 8 | robertsport
Processing Record 29 of Set 8 | lagoa
Processing Record 30 of Set 8 | isangel
Processing Record 31 of Set 8 | antofagasta
Processing Record 32 of Set 8 | sitka
Processing Record 33 of Set 8 | fairmont
Processing Record 34 of Set 8 | osvaldo cruz
Processing Record 35 of Set 8 | muli
Processing Record 36 of Set 8 | chuguyevka
Processing Record 37 of Set 8 | lubao
Processing Record 38 of Set 8 | beira
Processing Record 39 of Set 8 | culebra
Processing Record 40 of Set 8 | bubaque
Processing Record 41 of Set 8 | zheshart
Processing Record 42 of Set 8 | goodyear
Processing Record 43 of Set 8 | tiarei
Processing Record 44 of Set 8 | itanhaem
Processing Record 45 of Set 8 | gumdag
Processing Record 46 of Set 8 | marzuq
Processing Record 47 of Set 8 | yumen
Processing Record 48 of Set 8 | ambilobe
Processing Record 49 of Set 8 | udomlya
Processing Record 50 of Set 8 | magdagachi
Processing Record 1 of Set 9 | vallenar
Processing Record 2 of Set 9 | touros
Processing Record 3 of Set 9 | sergeyevka
Processing Record 4 of Set 9 | hofn
Processing Record 5 of Set 9 | chachapoyas
Processing Record 6 of Set 9 | coffeyville
Processing Record 7 of Set 9 | nouadhibou
Processing Record 8 of Set 9 | padang
Processing Record 9 of Set 9 | tsuruoka
Processing Record 10 of Set 9 | morros
Processing Record 11 of Set 9 | hirara
Processing Record 12 of Set 9 | diffa
Processing Record 13 of Set 9 | tieli
Processing Record 14 of Set 9 | ouadda
Processing Record 15 of Set 9 | maku
Processing Record 16 of Set 9 | nanyang
Processing Record 17 of Set 9 | altamira
Processing Record 18 of Set 9 | imbituba
Processing Record 19 of Set 9 | koraput
Processing Record 20 of Set 9 | fonte boa
Processing Record 21 of Set 9 | kununurra
Processing Record 22 of Set 9 | la rioja
Processing Record 23 of Set 9 | tautira
Processing Record 24 of Set 9 | thunder bay
Processing Record 25 of Set 9 | yarmouth
Processing Record 26 of Set 9 | talaya
Processing Record 27 of Set 9 | poso
Processing Record 28 of Set 9 | haines junction
Processing Record 29 of Set 9 | lander
Processing Record 30 of Set 9 | fort nelson
Processing Record 31 of Set 9 | moyale
Processing Record 32 of Set 9 | dhidhdhoo
Processing Record 33 of Set 9 | muravlenko
Processing Record 34 of Set 9 | quatre cocos
Processing Record 35 of Set 9 | kirakira
Processing Record 36 of Set 9 | hualmay
Processing Record 37 of Set 9 | puerto escondido
Processing Record 38 of Set 9 | itaituba
Processing Record 39 of Set 9 | jining
Processing Record 40 of Set 9 | uarini
Processing Record 41 of Set 9 | carlisle
Processing Record 42 of Set 9 | bukene
Processing Record 43 of Set 9 | morgan city
Processing Record 44 of Set 9 | ekimchan
Processing Record 45 of Set 9 | helena
Processing Record 46 of Set 9 | sobolevo
Processing Record 47 of Set 9 | sumbawa
City not found. Skipping...
Processing Record 48 of Set 9 | lodja
Processing Record 49 of Set 9 | perth
Processing Record 50 of Set 9 | yatou
Processing Record 1 of Set 10 | baoning
Processing Record 2 of Set 10 | koutiala
Processing Record 3 of Set 10 | manoel urbano
Processing Record 4 of Set 10 | san carlos
Processing Record 5 of Set 10 | najran
Processing Record 6 of Set 10 | fuyu
Processing Record 7 of Set 10 | filadelfia
Processing Record 8 of Set 10 | tuatapere
Processing Record 9 of Set 10 | killarney
Processing Record 10 of Set 10 | raton
Processing Record 11 of Set 10 | felidhoo
City not found. Skipping...
Processing Record 12 of Set 10 | luangwa
Processing Record 13 of Set 10 | narsaq
Processing Record 14 of Set 10 | huanren
Processing Record 15 of Set 10 | nanchang
Processing Record 16 of Set 10 | san carlos de bariloche
Processing Record 17 of Set 10 | gigmoto
Processing Record 18 of Set 10 | baherden
Processing Record 19 of Set 10 | general mamerto natividad
Processing Record 20 of Set 10 | saint-georges
Processing Record 21 of Set 10 | kerema
Processing Record 22 of Set 10 | lasa
Processing Record 23 of Set 10 | shakawe
Processing Record 24 of Set 10 | aklavik
Processing Record 25 of Set 10 | ventspils
Processing Record 26 of Set 10 | kabanjahe
Processing Record 27 of Set 10 | sumbe
Processing Record 28 of Set 10 | bay roberts
Processing Record 29 of Set 10 | ingham
Processing Record 30 of Set 10 | alta floresta
Processing Record 31 of Set 10 | lamu
Processing Record 32 of Set 10 | hoskote
Processing Record 33 of Set 10 | qasigiannguit
Processing Record 34 of Set 10 | amapa
Processing Record 35 of Set 10 | yarada
Processing Record 36 of Set 10 | formoso do araguaia
City not found. Skipping...
Processing Record 37 of Set 10 | chicama
Processing Record 38 of Set 10 | vila franca do campo
Processing Record 39 of Set 10 | manakara
Processing Record 40 of Set 10 | aranos
Processing Record 41 of Set 10 | omsukchan
Processing Record 42 of Set 10 | namtsy
Processing Record 43 of Set 10 | mayo
Processing Record 44 of Set 10 | new smyrna beach
Processing Record 45 of Set 10 | flinders
Processing Record 46 of Set 10 | ahar
Processing Record 47 of Set 10 | mount pleasant
Processing Record 48 of Set 10 | kabarnet
Processing Record 49 of Set 10 | iwanai
Processing Record 50 of Set 10 | timon
Processing Record 1 of Set 11 | nizhneyansk
City not found. Skipping...
Processing Record 2 of Set 11 | faya
Processing Record 3 of Set 11 | puerto ayacucho
Processing Record 4 of Set 11 | leninskoye
Processing Record 5 of Set 11 | tabou
Processing Record 6 of Set 11 | labuhan
Processing Record 7 of Set 11 | luanda
Processing Record 8 of Set 11 | umzimvubu
City not found. Skipping...
Processing Record 9 of Set 11 | coquimbo
Processing Record 10 of Set 11 | chernyshevskiy
Processing Record 11 of Set 11 | nuuk
Processing Record 12 of Set 11 | boende
Processing Record 13 of Set 11 | khani
Processing Record 14 of Set 11 | kloulklubed
Processing Record 15 of Set 11 | menongue
Processing Record 16 of Set 11 | mogadishu
Processing Record 17 of Set 11 | jardim
Processing Record 18 of Set 11 | rocha
Processing Record 19 of Set 11 | nantucket
Processing Record 20 of Set 11 | charlestown
Processing Record 21 of Set 11 | muzhi
Processing Record 22 of Set 11 | buckeye
Processing Record 23 of Set 11 | vila velha
Processing Record 24 of Set 11 | boyolangu
Processing Record 25 of Set 11 | okha
Processing Record 26 of Set 11 | olenino
Processing Record 27 of Set 11 | rolim de moura
City not found. Skipping...
Processing Record 28 of Set 11 | argenta
Processing Record 29 of Set 11 | lokhvytsya
Processing Record 30 of Set 11 | olimpia
Processing Record 31 of Set 11 | vanavara
Processing Record 32 of Set 11 | morant bay
Processing Record 33 of Set 11 | capanema
Processing Record 34 of Set 11 | la ronge
Processing Record 35 of Set 11 | pacific grove
Processing Record 36 of Set 11 | muisne
Processing Record 37 of Set 11 | cobija
Processing Record 38 of Set 11 | camocim
Processing Record 39 of Set 11 | tilichiki
Processing Record 40 of Set 11 | arman
Processing Record 41 of Set 11 | sierra madre
Processing Record 42 of Set 11 | mme
City not found. Skipping...
Processing Record 43 of Set 11 | itupiranga
Processing Record 44 of Set 11 | havoysund
Processing Record 45 of Set 11 | moose factory
Processing Record 46 of Set 11 | auki
Processing Record 47 of Set 11 | russell
Processing Record 48 of Set 11 | vostok
Processing Record 49 of Set 11 | almaznyy
Processing Record 50 of Set 11 | shivrajpur
Processing Record 1 of Set 12 | zempoala
Processing Record 2 of Set 12 | qui nhon
Processing Record 3 of Set 12 | brokopondo
Processing Record 4 of Set 12 | gorontalo
Processing Record 5 of Set 12 | ballina
Processing Record 6 of Set 12 | gazanjyk
Processing Record 7 of Set 12 | broken hill
Processing Record 8 of Set 12 | vaitupu
City not found. Skipping...
Processing Record 9 of Set 12 | aberystwyth
Processing Record 10 of Set 12 | wonthaggi
Processing Record 11 of Set 12 | chaoyang
Processing Record 12 of Set 12 | dong xoai
Processing Record 13 of Set 12 | puro
Processing Record 14 of Set 12 | yaring
Processing Record 15 of Set 12 | lithgow
Processing Record 16 of Set 12 | bereda

Processing Record 17 of Set 12 | french harbor
Processing Record 18 of Set 12 | yirol
City not found. Skipping...
Processing Record 19 of Set 12 | missoula
Processing Record 20 of Set 12 | bakchar
Processing Record 21 of Set 12 | san jose
Processing Record 22 of Set 12 | uinskoye
Processing Record 23 of Set 12 | ust-omchug
Processing Record 24 of Set 12 | yomitan
City not found. Skipping...
Processing Record 25 of Set 12 | xingyi
Processing Record 26 of Set 12 | derzhavinsk
Processing Record 27 of Set 12 | tacuarembo
Processing Record 28 of Set 12 | umm bab
Processing Record 29 of Set 12 | laguna
Processing Record 30 of Set 12 | mezen
Processing Record 31 of Set 12 | havre-saint-pierre
Processing Record 32 of Set 12 | concordia
Processing Record 33 of Set 12 | mbalmayo
Processing Record 34 of Set 12 | bone
Processing Record 35 of Set 12 | zalantun
Processing Record 36 of Set 12 | lata
Processing Record 37 of Set 12 | pozo colorado
Processing Record 38 of Set 12 | husavik
Processing Record 39 of Set 12 | chapayevka
Processing Record 40 of Set 12 | la oroya
Processing Record 41 of Set 12 | shingu
Processing Record 42 of Set 12 | mizdah
Processing Record 43 of Set 12 | timbiqui
Processing Record 44 of Set 12 | wamba
Processing Record 45 of Set 12 | yulara
Processing Record 46 of Set 12 | pundaguitan
--------------------
Data Retrieval is Complete
--------------------

In [24]:
len(city_data)

550

In [25]:
# change list of dictionaries into a dataframe
city_data_df = pd.DataFrame(city_data)
city_data_df.head(10)

,City,Lat,Lng,Max Temp,Current Description,Rain (inches),Snow (inches),Humidity,Cloudiness,Wind Speed,Country
0,ler,8.30,30.14,80.26,broken clouds,0.0,0.0,71,80,5.95,SS
1,mount gambier,-37.83,140.77,53.60,overcast clouds,0.0,0.0,81,90,11.41,AU
2,chokurdakh,70.63,147.92,91.42,scattered clouds,0.0,0.0,17,43,7.34,RU
3,tateyama,34.98,139.87,77.00,broken clouds,0.0,0.0,69,75,12.75,JP
4,kaman,27.65,77.27,110.08,clear sky,0.0,0.0,21,4,15.19,IN
5,ushuaia,-54.80,-68.30,35.60,overcast clouds,0.0,0.0,93,99,4.70,AR
6,villarrica,-25.75,-56.43,68.54,clear sky,0.0,0.0,78,0,5.10,PY
7,necochea,-38.55,-58.74,43.00,clear sky,0.0,0.0,83,10,3.00,AR
8,luganville,-15.53,167.17,78.80,broken clouds,0.0,0.0,83,75,3.36,VU
9,jamestown,42.10,-79.24,62.60,mist,0.0,0.0,93,1,0.74,US

In [26]:
city_data_df.columns

Index(['City', 'Lat', 'Lng', 'Max Temp', 'Current Description',
       'Rain (inches)', 'Snow (inches)', 'Humidity', 'Cloudiness',
       'Wind Speed', 'Country'],
      dtype='object')

In [27]:
new_column_order = sorted(city_data_df.columns.tolist())
city_data_df = city_data_df[new_column_order]
city_data_df

,City,Cloudiness,Country,Current Description,Humidity,Lat,Lng,Max Temp,Rain (inches),Snow (inches),Wind Speed
0,ler,80,SS,broken clouds,71,8.30,30.14,80.26,0.00,0.00,5.95
1,mount gambier,90,AU,overcast clouds,81,-37.83,140.77,53.60,0.00,0.00,11.41
2,chokurdakh,43,RU,scattered clouds,17,70.63,147.92,91.42,0.00,0.00,7.34
3,tateyama,75,JP,broken clouds,69,34.98,139.87,77.00,0.00,0.00,12.75
4,kaman,4,IN,clear sky,21,27.65,77.27,110.08,0.00,0.00,15.19
...,...,...,...,...,...,...,...,...,...,...,...
545,mizdah,0,LY,clear sky,13,31.45,12.98,86.58,0.00,0.00,13.06
546,timbiqui,90,CO,overcast clouds,92,2.77,-77.67,75.16,0.00,0.00,2.80
547,wamba,92,NG,light rain,92,8.93,8.60,72.43,0.14,0.14,2.80
548,yulara,0,AU,clear sky,29,-25.24,130.99,68.00,0.00,0.00,5.82
549,pundaguitan,100,PH,light rain,78,6.37,126.17,83.08,0.77,0.77,15.23

In [28]:
city_data_df.dtypes

City                    object
Cloudiness               int64
Country                 object
Current Description     object
Humidity                 int64
Lat                    float64
Lng                    float64
Max Temp               float64
Rain (inches)          float64
Snow (inches)          float64
Wind Speed             float64
dtype: object

In [32]:
raining_cities = city_data_df.loc[city_data_df["Rain (inches)"] > 0]
raining_cities.head()

,City,Cloudiness,Country,Current Description,Humidity,Lat,Lng,Max Temp,Rain (inches),Snow (inches),Wind Speed
12,katete,41,UG,light rain,83,-0.78,29.75,67.57,0.12,0.12,0.56
28,tutoia,22,BR,light rain,90,-2.76,-42.27,75.34,0.70,0.70,8.90
70,sinnamary,11,GF,light rain,88,5.38,-52.95,77.83,0.60,0.60,7.25
77,airai,99,TL,light rain,77,-8.93,125.41,70.12,0.13,0.13,5.75
79,cidreira,76,BR,light rain,95,-30.18,-50.21,65.48,0.88,0.88,3.42

In [33]:
snowing_cities = city_data_df.loc[city_data_df["Snow (inches)"] > 0]
snowing_cities.head()

,City,Cloudiness,Country,Current Description,Humidity,Lat,Lng,Max Temp,Rain (inches),Snow (inches),Wind Speed
12,katete,41,UG,light rain,83,-0.78,29.75,67.57,0.12,0.12,0.56
28,tutoia,22,BR,light rain,90,-2.76,-42.27,75.34,0.70,0.70,8.90
70,sinnamary,11,GF,light rain,88,5.38,-52.95,77.83,0.60,0.60,7.25
77,airai,99,TL,light rain,77,-8.93,125.41,70.12,0.13,0.13,5.75
79,cidreira,76,BR,light rain,95,-30.18,-50.21,65.48,0.88,0.88,3.42

In [34]:
# Create the output csv file
output_data_file = "data/WeatherPy_Database.csv"
city_data_df.to_csv(output_data_file, index_label = "City ID")